version: "3"

services:
  paddle_serving:
    image: lianshufeng/paddle_serving:gpu
    volumes:
      - "./inference_model:/Serving"
    ports:
      - "9999:8888"
    container_name: paddle_serving
    restart: always
    command: python -m paddle_serving_server.serve --model serving_server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]