version: "3"

services:
  paddle_serving:
    image: lianshufeng/paddle_serving
    volumes:
      - "./inference_model:/Serving"
    ports:
      - "9292:9292"
    container_name: paddle_serving
    restart: always