version: "3"

services:
  paddle_serving:
    image: lianshufeng/paddle_serving:gpu
    volumes:
      - "./inference_model:/Serving"
    ports:
      - "9393:9393"
    container_name: paddle_serving
    restart: always
    command: python -m paddle_serving_server.serve --model serving_server --port 9393 --thread 8 --gpu_ids 0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]